controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - waist_joint
      - lower_arm_joint
      - upper_arm_joint
      - wrist_joint
      - gripper_base_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - left_gear_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: intial_pose
  - group: gripper
    pose: gripper_open