arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - waist_joint
    - lower_arm_joint
    - upper_arm_joint
    - wrist_joint
    - gripper_base_joint
  gains:
    waist_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    lower_arm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    upper_arm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_gear_joint
  gains:
    left_gear_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
controller_list:
  - name: mocha/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - waist_joint
      - lower_arm_joint
      - upper_arm_joint
      - wrist_joint
      - gripper_base_joint
  - name: mocha/gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - left_gear_joint