mocha:

  # Arm Trajectory Controllers ---------------------------------------
  arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - waist_joint
      - lower_arm_joint
      - upper_arm_joint
      - wrist_joint
      - gripper_base_joint


  # Gripper Trajectory Controllers ---------------------------------------
  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - left_gear_joint